# Generated by Django 3.2.9 on 2022-01-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=300)),
                ('q1', models.TextField()),
                ('q1s', models.BooleanField()),
                ('q2', models.TextField()),
                ('q2s', models.BooleanField()),
                ('q3', models.TextField()),
                ('q3s', models.BooleanField()),
                ('q4', models.TextField()),
                ('q4s', models.BooleanField()),
            ],
        ),
    ]
